// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edxurdwjvybypuyltyew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkeHVyZHdqdnlieXB1eWx0eWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTgzODksImV4cCI6MjA2NDM3NDM4OX0.KJ6ml6WedSdHhmf-GMtRpAMJC-iO4CbP4YJEzirYGKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);